### ISSUE TITLE
Plan & Journal

### ISSUE THREAD

**Issue by larryxiao** [larryxiao/libflatarray#6]
## SIMD Wrapper for ARM NEON, Intel AVX512 & KNC
- Pre GSoC ( - 26 April)
  - [X] [Study the HPX, libflatarray codebase](https://github.com/larryxiao/libflatarray/issues/1)
- Community Bonding Period (27 April - 24 May)
  - [ ] Discuss with mentor about the architectures to support (ARM NEON, Intel AVX512, Intel IMCI, CUDA, or KNC), and regard each as sub-project. 
    - [ ] [Sub-project 1: Support for ARM NEON · Issue #2 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/2)
    - [ ] [Sub-project 2: Support for Intel AVX512 · Issue #3 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/3)
    - [ ] [Sub-project 3: Support for Intel IMCI · Issue #4 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/4)
- Week 1, 2 (25 May - 7 June)
  - [ ] Write detailed implementation plans about sub-projects, and refine with help from mentor.
  - [ ] Implement key functions in the project, get approval from mentor.
- Week 3, 4 (8 June - 21 June)
  - [ ] Implement sub-projects 1-3, 2 weeks per sub-project.
  - [ ] Submit midterm evaluation (26 June)
- Week 5, 6 (22 June - 5 July)
  - [ ] Testing for sub-projects 1-3, ensure correctness
- Week 7, 8 (6 July - 19 July)
  - [ ] Evaluate performance, then optimize
- Week 9, 10 (20 July - 2 August))
  - [ ] Implement more sub-projects, depends on plan.
- Week 11, 12 (3 August - 21 August)
  - [ ] Testing, improve documentation
  - [ ] Submit final evaluation (28 August)
- (Remain one week available for allocation)
## Plan

First implement a prototype for a new vectorization architecture, eg. float 4. Then test the prototype, make sure it's correct. Then expand into more data types, like float 8, float 16, and double.

**Comment by larryxiao** [comment]
### Pre GSoC ( - 26 April)
- [Study: HPX, libflatarray · Issue #1 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/1)
- Written concept code with ARM NEON

### Community Bonding Period (27 April - 24 May)
- Write code for ARM NEON float_4, compile (cross compiled), not tested yet
- Setup toolchain for AVX 512, run sample code with Intel SDE

## Week 1 May 25 - May 31
- [In progress] [Study: related project, and proposals · Issue #5 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/5)

## Week 2 Jun 1 - Jun 7
- [done] [Study: related project, and proposals · Issue #5 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/5)

## Week 3 Jun 8 - Jun 14
- [AVX512] compile avx512 code with Intel compiler

## Week 4 Jun 15 - Jun 21
- set up testing environment
- IMCI prototype code

## Week 5 Jun 22 - Jun 28
- merge with bitbucket upstream, convert git to mercurial
- compile on jetson: compile flag, include path
- implement new functions: load/store aligned, store_nt, gather scatter
- mid term evaluation

## Week 6 Jun 29 - July 5
- test NEON on jetson

## Week 7  July 6 - July 12
- week off (graduation)

## Week 8  July 13 - July 19
- NEON: non-temporal store, aligned load/store, gather, scatter
- implementation and test

## Week 9 July 20 - July 26

**Comment by larryxiao** [comment]
### Week 1 May 25 - May 31
* [Study: related project, and proposals · Issue #5 · larryxiao/libflatarray](https://github.com/larryxiao/libflatarray/issues/5)

**Comment by larryxiao** [comment]
## Question
- [x] In `short_vec` there's only support for floating point data types. How does libflatarray support integer?
- [ ] What does `libflatarray/detail/sqrt_reference.hpp` do?
